// <auto-generated>
// This code is generated by csbindgen.
// DON'T CHANGE THIS DIRECTLY.
// </auto-generated>
#pragma warning disable CS8500
#pragma warning disable CS8981
using System;
using System.Runtime.InteropServices;


namespace StorageIntelligence.Native
{
    internal static unsafe partial class NativeMethods
    {
        const string __DllName = "ffi";





        /// <summary>
        ///  Idempotent; called automatically on first use, and may also be called explicitly
        ///  by the host at startup. Owns the single `tracing` subscriber init point (ADR-005).
        /// </summary>
        [DllImport(__DllName, EntryPoint = "init_logging", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void init_logging();

        /// <summary>
        ///  Frees a message allocated by `scan_drive` via `set_error_message`. Safe to call with
        ///  a null pointer (no-op).
        ///
        ///  # Safety
        ///  `ptr` must be null, or a pointer previously returned by this crate via an
        ///  `out_error_message` parameter, and must not have been freed already.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "free_error_message", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void free_error_message(ushort* ptr);

        [DllImport(__DllName, EntryPoint = "cancel_token_create", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern CancelHandle* cancel_token_create();

        /// <summary>
        ///  # Safety
        ///  `handle` must be null or a valid pointer previously returned by `cancel_token_create`
        ///  that has not yet been destroyed.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "cancel_token_cancel", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void cancel_token_cancel(CancelHandle* handle);

        /// <summary>
        ///  # Safety
        ///  `handle` must be null or a valid pointer previously returned by `cancel_token_create`,
        ///  must not be used again after this call, and must not be destroyed twice.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "cancel_token_destroy", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void cancel_token_destroy(CancelHandle* handle);

        /// <summary>
        ///  Blocking C ABI entry point (ADR-007): call from a background thread (e.g. a .NET
        ///  `Task.Run`), never the UI thread. `cancel_handle` may be cancelled concurrently from
        ///  another thread. On success, `*out_result` receives an owned `ScanResultHandle` the
        ///  caller must eventually pass to `scan_result_destroy`. On failure, `*out_error_message`
        ///  (if non-null) receives an owned message the caller must pass to `free_error_message`.
        ///
        ///  # Safety
        ///  `path` must be null or a valid null-terminated UTF-16 string pointer. `cancel_handle`
        ///  must be a valid pointer from `cancel_token_create`. `out_result` and
        ///  `out_error_message` must each be valid, writable pointers (or null for the latter).
        /// </summary>
        [DllImport(__DllName, EntryPoint = "scan_drive", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int scan_drive(ushort* path, CancelHandle* cancel_handle, delegate* unmanaged[Cdecl]<ScanProgressFfi, void*, void> progress_callback, void* user_data, ScanResultHandle** out_result, ushort** out_error_message);

        /// <summary>
        ///  # Safety
        ///  `handle` must be null or a valid pointer previously returned by `scan_drive` via
        ///  `out_result`, and must not have been destroyed.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "scan_result_summary", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern ScanSummaryFfi scan_result_summary(ScanResultHandle* handle);

        /// <summary>
        ///  # Safety
        ///  `handle` must be null or a valid pointer previously returned by `scan_drive` via
        ///  `out_result`, must not be used again after this call, and must not be destroyed twice.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "scan_result_destroy", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void scan_result_destroy(ScanResultHandle* handle);

        /// <summary>
        ///  Build a `StorageTree` from the events in `scan_result`. The events are **moved**
        ///  (not copied) out of the `ScanResultHandle`; calling `tree_create` a second time
        ///  on the same result handle returns `ScanErrorCode::Internal`.
        ///
        ///  On success, `*out_tree` receives an owned `TreeHandle`. The caller must eventually
        ///  pass it to `tree_destroy`.
        ///
        ///  # Safety
        ///  `scan_result` must be a valid, non-null pointer from `scan_drive`. `out_tree` must
        ///  be a valid, writable pointer.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "tree_create", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int tree_create(ScanResultHandle* scan_result, TreeHandle** out_tree, ushort** out_error_message);

        /// <summary>
        ///  # Safety
        ///  `handle` must be null or a valid pointer from `tree_create`, not yet destroyed.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "tree_destroy", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void tree_destroy(TreeHandle* handle);

        /// <summary>
        ///  Returns the root node ID, or `u64::MAX` on error.
        ///
        ///  # Safety
        ///  `handle` must be a valid pointer returned by `tree_create`.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "tree_root_id", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern ulong tree_root_id(TreeHandle* handle);

        /// <summary>
        ///  Returns the total number of nodes in the tree, or 0 on error.
        ///
        ///  # Safety
        ///  `handle` must be a valid pointer returned by `tree_create`.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "tree_node_count", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern ulong tree_node_count(TreeHandle* handle);

        /// <summary>
        ///  Get info for a single node. Returns 0 on success, non-zero if invalid.
        ///
        ///  # Safety
        ///  `handle` must be valid from `tree_create`. `out_info` must be a valid, writable pointer.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "tree_node_info", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int tree_node_info(TreeHandle* handle, ulong node_id, NodeInfoFfi* out_info);

        /// <summary>
        ///  Get children of a node (pre-sorted by size desc). Paginated via offset/limit.
        ///
        ///  # Safety
        ///  `out_ids` must point to a buffer of at least `limit` u64s. `out_count` and
        ///  `out_total_children` must be valid, writable pointers.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "tree_children", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int tree_children(TreeHandle* handle, ulong node_id, uint offset, uint limit, ulong* out_ids, uint* out_count, uint* out_total_children);

        /// <summary>
        ///  Get ancestors of a node (bottom-up: node → parent → ... → root).
        ///
        ///  # Safety
        ///  `out_ids` must point to a buffer of at least `limit` u64s.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "tree_ancestors", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int tree_ancestors(TreeHandle* handle, ulong node_id, ulong* out_ids, uint limit, uint* out_count);

        /// <summary>
        ///  Get top N largest files under a subtree.
        ///
        ///  # Safety
        ///  `out_ids` must point to a buffer of at least `limit` u64s.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "tree_top_files_by_size", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int tree_top_files_by_size(TreeHandle* handle, ulong root_id, uint limit, ulong* out_ids, uint* out_count);

        /// <summary>
        ///  Copies the node's name as null-terminated UTF-16 into `out_buffer`.
        ///  `buffer_len` is in u16 units (including null terminator).
        ///  `*out_actual_len` receives the UTF-16 length in characters (excluding null terminator).
        ///
        ///  # Safety
        ///  `handle` must be valid from `tree_create`. `out_actual_len` must be a valid, writable pointer.
        ///  If `out_buffer` is non-null, it must point to writable memory of at least `buffer_len` u16s.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "tree_node_name", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int tree_node_name(TreeHandle* handle, ulong node_id, ushort* out_buffer, uint buffer_len, uint* out_actual_len);

        /// <summary>
        ///  Reconstructs the node's full path as null-terminated UTF-16 into `out_buffer`.
        ///  `buffer_len` is in u16 units (including null terminator).
        ///  `*out_actual_len` receives the UTF-16 length in characters (excluding null terminator).
        ///
        ///  # Safety
        ///  `handle` must be valid from `tree_create`. `out_actual_len` must be a valid, writable pointer.
        ///  If `out_buffer` is non-null, it must point to writable memory of at least `buffer_len` u16s.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "tree_node_path", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int tree_node_path(TreeHandle* handle, ulong node_id, ushort* out_buffer, uint buffer_len, uint* out_actual_len);

        /// <summary>
        ///  Finds a node by absolute filesystem path within the active StorageTree.
        ///  Returns Ok (0) and writes the node_id to `*out_node_id`, or InvalidPath if not found.
        ///
        ///  # Safety
        ///  `handle`, `path`, and `out_node_id` must be valid non-null pointers.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "tree_find_by_path", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int tree_find_by_path(TreeHandle* handle, ushort* path, ulong* out_node_id);

        /// <summary>
        ///  Computes squarified treemap layout starting from `root_id` into `out_rects`.
        ///  `limit` is the capacity of the `out_rects` buffer in elements.
        ///  `*out_count` receives the number of rectangles written into `out_rects`.
        ///  `*out_total_rects` receives the total number of rectangles generated by the layout.
        ///
        ///  # Safety
        ///  `handle` must be valid from `tree_create`. `out_count` and `out_total_rects` must be valid, writable pointers.
        ///  If `limit &gt; 0` and `out_rects` is non-null, it must point to a buffer of at least `limit` TreemapRectFfi items.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "tree_compute_layout", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int tree_compute_layout(TreeHandle* handle, ulong root_id, float width, float height, uint max_depth, float min_size_px, TreemapRectFfi* out_rects, uint limit, uint* out_count, uint* out_total_rects);

        /// <summary>
        ///  Searches the StorageTree arena using the given query (ADR-012).
        ///  Supports tokenized filters (ext:, size:, type:, kind:) and space-aware ranking.
        ///
        ///  # Safety
        ///  `handle` must be valid from `tree_create`. `query` must be a null-terminated UTF-16 string.
        ///  `out_count` must be a valid, writable pointer.
        ///  If `limit &gt; 0` and `out_results` is non-null, it must point to a buffer of at least `limit` SearchResultFfi items.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "tree_search", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int tree_search(TreeHandle* handle, ushort* query, uint limit, SearchResultFfi* out_results, uint* out_count);

        /// <summary>
        ///  Detects all cleanup candidate categories across the active in-memory tree (ADR-013).
        ///
        ///  # Safety
        ///  `handle` must be a valid pointer from `tree_create`. `out_count` and `out_total` must be valid writable pointers.
        ///  If `limit &gt; 0` and `out_candidates` is non-null, it must point to a buffer of at least `limit` CleanupCandidateFfi items.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "cleanup_detect_candidates", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int cleanup_detect_candidates(TreeHandle* handle, CleanupCandidateFfi* out_candidates, uint limit, uint* out_count, uint* out_total);

        /// <summary>
        ///  Executes or simulates cleanup for a specific candidate category (ADR-013).
        ///  Enforces safety invariants: protected paths are rejected, deletions default to Recycle Bin.
        ///
        ///  # Safety
        ///  `handle` must be a valid pointer from `tree_create`. `out_report` must be a valid writable pointer.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "cleanup_execute_rule", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int cleanup_execute_rule(TreeHandle* handle, uint rule_id, byte dry_run, byte send_to_recycle_bin, CleanupReportFfi* out_report);

        /// <summary>
        ///  Checks if a filesystem path is an unbypassable protected system location (ADR-013).
        ///
        ///  # Safety
        ///  `path` must be a null-terminated UTF-16 string pointer.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "cleanup_is_path_protected", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern byte cleanup_is_path_protected(ushort* path);

        /// <summary>
        ///  Discovers installed applications and attributes storage using the active tree (ADR-014).
        ///  `tree_handle` is optional (may be null).
        ///  `*out_catalog` receives an owned handle the caller must destroy via `app_catalog_destroy`.
        ///
        ///  # Safety
        ///  `out_catalog` must be a valid, writable pointer.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "app_catalog_create", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int app_catalog_create(TreeHandle* tree_handle, AppCatalogHandle** out_catalog);

        /// <summary>
        ///  Returns the number of applications in the catalog.
        ///
        ///  # Safety
        ///  `catalog` must be null or a valid pointer from `app_catalog_create`.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "app_catalog_count", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern uint app_catalog_count(AppCatalogHandle* catalog);

        /// <summary>
        ///  Retrieves metadata numbers for the application at `index`.
        ///
        ///  # Safety
        ///  `catalog` must be valid from `app_catalog_create`. `out_info` must be a valid writable pointer.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "app_catalog_item", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int app_catalog_item(AppCatalogHandle* catalog, uint index, AppInfoFfi* out_info);

        /// <summary>
        ///  Retrieves a string field for the application at `index`.
        ///  `field_id`: 0=id, 1=name, 2=version, 3=publisher, 4=install_location,
        ///  5=uninstall_string, 6=quiet_uninstall_string, 7=install_date.
        ///
        ///  # Safety
        ///  `catalog` and `out_actual_len` must be valid pointers.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "app_catalog_string", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int app_catalog_string(AppCatalogHandle* catalog, uint index, uint field_id, ushort* out_buffer, uint buffer_len, uint* out_actual_len);

        /// <summary>
        ///  Frees an `AppCatalogHandle`. Safe to call with null.
        ///
        ///  # Safety
        ///  `catalog` must be null or a valid pointer from `app_catalog_create`.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "app_catalog_destroy", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void app_catalog_destroy(AppCatalogHandle* catalog);

        /// <summary>
        ///  Detects orphaned application leftovers (ADR-014 §4).
        ///
        ///  # Safety
        ///  `out_leftovers` must be a valid, writable pointer.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "app_leftovers_detect", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int app_leftovers_detect(AppCatalogHandle* catalog, TreeHandle* tree_handle, AppLeftoversHandle** out_leftovers);

        /// <summary>
        ///  Returns the number of leftovers found.
        ///
        ///  # Safety
        ///  `leftovers` must be null or a valid pointer from `app_leftovers_detect`.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "app_leftovers_count", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern uint app_leftovers_count(AppLeftoversHandle* leftovers);

        /// <summary>
        ///  Retrieves metadata numbers for the leftover at `index`.
        ///
        ///  # Safety
        ///  `leftovers` and `out_info` must be valid pointers.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "app_leftovers_item", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int app_leftovers_item(AppLeftoversHandle* leftovers, uint index, AppLeftoverFfi* out_info);

        /// <summary>
        ///  Retrieves string fields for the leftover at `index`.
        ///  `field_id`: 0=id, 1=app_name, 2=path.
        ///
        ///  # Safety
        ///  `leftovers` and `out_actual_len` must be valid pointers.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "app_leftovers_string", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int app_leftovers_string(AppLeftoversHandle* leftovers, uint index, uint field_id, ushort* out_buffer, uint buffer_len, uint* out_actual_len);

        /// <summary>
        ///  Frees an `AppLeftoversHandle`. Safe to call with null.
        ///
        ///  # Safety
        ///  `leftovers` must be null or a valid pointer from `app_leftovers_detect`.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "app_leftovers_destroy", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void app_leftovers_destroy(AppLeftoversHandle* leftovers);

        /// <summary>
        ///  Discovers developer artifacts across the active StorageTree and canonical Windows dev paths (ADR-015).
        ///  `tree_handle` is optional (may be null).
        ///  `*out_catalog` receives an owned handle the caller must destroy via `dev_catalog_destroy`.
        ///
        ///  # Safety
        ///  `out_catalog` must be a valid, writable pointer.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "dev_catalog_create", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int dev_catalog_create(TreeHandle* tree_handle, DevCatalogHandle** out_catalog);

        /// <summary>
        ///  Returns the number of developer artifacts discovered.
        ///
        ///  # Safety
        ///  `catalog` must be null or a valid pointer from `dev_catalog_create`.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "dev_catalog_count", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern uint dev_catalog_count(DevCatalogHandle* catalog);

        /// <summary>
        ///  Retrieves numeric metadata for the developer artifact at `index`.
        ///
        ///  # Safety
        ///  `catalog` and `out_info` must be valid non-null pointers.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "dev_catalog_item", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int dev_catalog_item(DevCatalogHandle* catalog, uint index, DevArtifactFfi* out_info);

        /// <summary>
        ///  Retrieves a string field for the developer artifact at `index`.
        ///  `field_id`: 0=id, 1=name, 2=project_name, 3=path, 4=description, 5=cleanup_command.
        ///
        ///  # Safety
        ///  `catalog` and `out_actual_len` must be valid pointers.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "dev_catalog_string", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int dev_catalog_string(DevCatalogHandle* catalog, uint index, uint field_id, ushort* out_buffer, uint buffer_len, uint* out_actual_len);

        /// <summary>
        ///  Frees a `DevCatalogHandle`. Safe to call with null.
        ///
        ///  # Safety
        ///  `catalog` must be null or a valid pointer from `dev_catalog_create`.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "dev_catalog_destroy", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void dev_catalog_destroy(DevCatalogHandle* catalog);

        /// <summary>
        ///  Safely cleans a developer artifact directory or cache (ADR-015 §4).
        ///  Enforces zero-accident guardrails (source files and git roots are rejected).
        ///
        ///  # Safety
        ///  `path` and `out_report` must be valid non-null pointers.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "dev_clean_artifact", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int dev_clean_artifact(ushort* path, byte dry_run, byte send_to_recycle_bin, CleanupReportFfi* out_report);

        /// <summary>
        ///  Persists an in-memory `StorageTree` hierarchy into the SQLite index (ADR-016).
        ///
        ///  # Safety
        ///  `db_path`, `tree_handle`, and `root_path` must be valid non-null pointers.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "index_save_tree", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int index_save_tree(ushort* db_path, TreeHandle* tree_handle, ushort* root_path);

        /// <summary>
        ///  Hydrates an in-memory `StorageTree` directly from the SQLite index in &lt; 100ms (ADR-016).
        ///
        ///  # Safety
        ///  `db_path`, `root_path`, and `out_tree` must be valid non-null pointers.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "index_load_tree", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int index_load_tree(ushort* db_path, ushort* root_path, TreeHandle** out_tree);

        /// <summary>
        ///  Incrementally synchronizes filesystem changes into the tree and database (ADR-016).
        ///
        ///  # Safety
        ///  `db_path`, `tree_handle`, `root_path`, and `out_report` must be valid non-null pointers.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "index_sync_tree", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int index_sync_tree(ushort* db_path, TreeHandle* tree_handle, ushort* root_path, IndexSyncReportFfi* out_report);

        /// <summary>
        ///  Retrieves indexed volume metrics (ADR-016).
        ///
        ///  # Safety
        ///  `db_path`, `root_path`, and `out_stats` must be valid non-null pointers.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "index_get_stats", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int index_get_stats(ushort* db_path, ushort* root_path, IndexStatsFfi* out_stats);

        /// <summary>
        ///  Deletes an indexed volume from SQLite (ADR-016).
        ///
        ///  # Safety
        ///  `db_path`, `root_path`, and `out_deleted` must be valid non-null pointers.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "index_delete_volume", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int index_delete_volume(ushort* db_path, ushort* root_path, byte* out_deleted);


    }

    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct ScanSummaryFfi
    {
        public ulong total_files;
        public ulong total_dirs;
        public ulong total_size;
        public ulong inaccessible_count;
    }

    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct ScanProgressFfi
    {
        public ulong files_scanned;
        public ulong bytes_scanned;
    }

    /// <summary>
    ///  Opaque handle wrapping a `CancellationToken`, owned by the caller until
    ///  `cancel_token_destroy`. Safe to call `cancel_token_cancel` from a different
    ///  thread than the one blocked inside `scan_drive` (ADR-007's threading model).
    /// </summary>
    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct CancelHandle
    {
    }

    /// <summary>
    ///  Opaque handle wrapping a completed scan's summary and event stream, owned by
    ///  the caller until `scan_result_destroy`. Events are consumed (moved) by
    ///  `tree_create` to build the storage tree (ADR-009 #5: two-handle lifecycle).
    /// </summary>
    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct ScanResultHandle
    {
    }

    /// <summary>
    ///  Opaque handle wrapping a built `StorageTree` (ADR-009). Owned by the caller
    ///  until `tree_destroy`. Thread-safe for concurrent reads.
    /// </summary>
    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct TreeHandle
    {
    }

    /// <summary>
    ///  C-compatible node info struct. Data is copied from the tree into this struct;
    ///  string pointers (`name`, `extension`) point into caller-provided buffers or
    ///  are encoded inline as UTF-16. For simplicity at MVP, names are copied into
    ///  a heap-allocated UTF-16 buffer that lives until `tree_destroy`.
    /// </summary>
    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct NodeInfoFfi
    {
        public ulong id;
        public ulong parent_id;
        public int kind;
        public ulong size;
        public ulong file_count;
        public ulong dir_count;
    }

    /// <summary>
    ///  C-compatible representation of a single laid-out rectangle in the treemap (ADR-010).
    /// </summary>
    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct TreemapRectFfi
    {
        public ulong node_id;
        public float x;
        public float y;
        public float width;
        public float height;
        public uint depth;
        public int kind;
        public int category;
    }

    /// <summary>
    ///  C-compatible representation of a search result hit (ADR-012).
    /// </summary>
    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct SearchResultFfi
    {
        public ulong node_id;
        public ulong size;
        public int kind;
        public int category;
        public uint score;
    }

    /// <summary>
    ///  C-compatible representation of a cleanup candidate group (ADR-013).
    /// </summary>
    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct CleanupCandidateFfi
    {
        public uint rule_id;
        public int risk_level;
        public ulong total_bytes;
        public ulong file_count;
        public byte is_protected;
    }

    /// <summary>
    ///  C-compatible execution report for a cleanup operation (ADR-013).
    /// </summary>
    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct CleanupReportFfi
    {
        public ulong files_reclaimed;
        public ulong bytes_reclaimed;
        public ulong files_failed;
        public byte is_dry_run;
    }

    /// <summary>
    ///  Opaque handle wrapping discovered applications (ADR-014).
    /// </summary>
    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct AppCatalogHandle
    {
    }

    /// <summary>
    ///  Opaque handle wrapping discovered leftovers (ADR-014).
    /// </summary>
    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct AppLeftoversHandle
    {
    }

    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct AppInfoFfi
    {
        public uint kind;
        public ulong estimated_size;
        public ulong actual_size;
        public ulong file_count;
        public byte is_system_component;
    }

    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct AppLeftoverFfi
    {
        public ulong size;
        public ulong file_count;
        public uint location_type;
        public int risk_level;
    }

    /// <summary>
    ///  Opaque handle wrapping discovered developer artifacts (ADR-015).
    /// </summary>
    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct DevCatalogHandle
    {
    }

    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct DevArtifactFfi
    {
        public uint ecosystem;
        public uint kind;
        public ulong size;
        public ulong file_count;
        public uint is_dormant;
        public uint days_inactive;
        public int risk_level;
    }

    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct IndexStatsFfi
    {
        public ulong volume_id;
        public ulong node_count;
        public ulong total_size;
        public ulong last_scan_time;
        public ulong last_usn;
    }

    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct IndexSyncReportFfi
    {
        public ulong nodes_added;
        public ulong nodes_updated;
        public ulong nodes_removed;
        public long bytes_delta;
        public ulong sync_duration_ms;
    }



}
